Create core of project
GB-Team-development-course/SecondTestRepository pull request #1
Opened 2022-07-02 15:35 UTC by AgentMorgan1990

2022-07-03 00:32 UTC, nxbeyxnd commented on core-service/src/main/resources/application.properties
> +# Ports
@AgentMorgan1990  давай изменим файл application.properties на *.yml формат, считаю его более читаемым

2022-07-03 00:33 UTC, nxbeyxnd requested changes
@AgentMorgan1990  давай изменим файл application.properties на *.yml формат, считаю его более читаемым

2022-07-03 08:50 UTC, thank267 reviewed
Написал пару замечаний по версиям spring-boot и lombok

2022-07-03 08:50 UTC, thank267 commented on pom.xml
> +		<version>2.5.6</version>
А зачем версию бута понижать? Договорились вроде последнюю испольлзовать

2022-07-03 08:50 UTC, thank267 commented on pom.xml
> +			<version>1.18.22</version>
Ну наверное и ломбок тогда по псоледней 1.18.24

2022-07-04 07:04 UTC, AgentMorgan1990 commented on core-service/src/main/resources/application.properties
> +# Ports
Ок. Согласен. Внёс изменения

2022-07-04 07:05 UTC, AgentMorgan1990 commented on pom.xml
> +		<version>2.5.6</version>
Вернул обратно 2.7.1

2022-07-04 07:05 UTC, AgentMorgan1990 commented on pom.xml
> +			<version>1.18.22</version>
Повысил версию до 1.18.24

2022-07-04 08:26 UTC, thank267 approved these changes
Вроже все ок

2022-07-04 08:28 UTC, nxbeyxnd approved these changes

2022-07-04 09:52 UTC, merged